---
- name: restart prometheus
  ansible.builtin.systemd:
    name: prometheus
    state: restarted
  become: true

- name: restart grafana
  ansible.builtin.systemd:
    name: grafana-server
    state: restarted
  become: true
