#!/usr/bin/env bash
# lib.sh - Shared functions for benchmark scripts
#
# Source this file from run_benchmark.sh, run_comparison.sh, etc.
# Provides: log, run_ansible, setup_env_from_inventory, reset_cluster_state,
#           cleanup_on_exit, run_scenarios

set -euo pipefail

# Guard against double-sourcing
if [[ -n "${_LIB_SH_LOADED:-}" ]]; then
    return 0
fi
_LIB_SH_LOADED=1

# ---------------------------------------------------------------------------
# Directory layout
# ---------------------------------------------------------------------------

SCRIPT_DIR="${SCRIPT_DIR:-$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)}"
BENCH_DIR="${BENCH_DIR:-$(cd "${SCRIPT_DIR}/.." && pwd)}"
ANSIBLE_DIR="${ANSIBLE_DIR:-${BENCH_DIR}/ansible}"

# ---------------------------------------------------------------------------
# Auto-source bench.env (generated by bootstrap.sh)
# ---------------------------------------------------------------------------

if [[ -f "${BENCH_DIR}/bench.env" ]]; then
    # shellcheck disable=SC1091
    source "${BENCH_DIR}/bench.env"
fi

# ---------------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------------

log() {
    local ts
    ts=$(date -u '+%Y-%m-%dT%H:%M:%SZ')
    echo "[$ts] $*" | tee -a "${LOG_FILE:-/dev/null}"
}

# ---------------------------------------------------------------------------
# Ansible helper
# ---------------------------------------------------------------------------

run_ansible() {
    local playbook="$1"; shift
    local inv_args=()
    if [[ -n "${ANSIBLE_INVENTORY:-}" ]]; then
        inv_args=(-i "${ANSIBLE_INVENTORY}")
    fi
    # Pass SSH key to Ansible if set
    if [[ -n "${SSH_KEY:-}" ]]; then
        export ANSIBLE_PRIVATE_KEY_FILE="$SSH_KEY"
    fi
    log "Running Ansible playbook: $playbook $*"
    (cd "${ANSIBLE_DIR}" && ansible-playbook "${inv_args[@]}" "${playbook}" "$@") 2>&1 | tee -a "${LOG_FILE:-/dev/null}"
}

# ---------------------------------------------------------------------------
# Preflight checks
# ---------------------------------------------------------------------------

preflight_check() {
    local errors=0

    # Required tools
    for cmd in ansible-playbook python3 ssh curl; do
        if ! command -v "$cmd" >/dev/null 2>&1; then
            log "ERROR: Required tool not found: $cmd"
            errors=$((errors + 1))
        fi
    done

    # Inventory file
    local inventory="${ANSIBLE_DIR}/inventory/hosts"
    if [[ -n "${ANSIBLE_INVENTORY:-}" ]]; then
        inventory="$ANSIBLE_INVENTORY"
    fi
    if [[ ! -f "$inventory" ]]; then
        log "ERROR: Inventory file not found: $inventory"
        log "       Run ./scripts/infra_up.sh to provision infrastructure first."
        errors=$((errors + 1))
    fi

    # SSH key
    if [[ -z "${SSH_KEY:-}" ]]; then
        log "WARNING: SSH_KEY is not set. SSH connections may fail."
        log "         Run ./scripts/bootstrap.sh or export SSH_KEY=/path/to/key.pem"
    elif [[ ! -f "$SSH_KEY" ]]; then
        log "ERROR: SSH_KEY file not found: $SSH_KEY"
        errors=$((errors + 1))
    fi

    if (( errors > 0 )); then
        log "Preflight check failed with $errors error(s)"
        exit 1
    fi

    log "Preflight check passed"
}

# ---------------------------------------------------------------------------
# Wait for SSH readiness on all nodes (for freshly provisioned instances)
# ---------------------------------------------------------------------------

wait_for_ssh() {
    local max_wait="${1:-180}"
    local ssh_key_arg=""
    if [[ -n "${SSH_KEY:-}" ]]; then
        ssh_key_arg="-i ${SSH_KEY}"
    fi

    local all_ips=""
    for var in VMQ_NODES BENCH_NODES; do
        if [[ -n "${!var:-}" ]]; then
            all_ips="${all_ips:+$all_ips }${!var}"
        fi
    done

    if [[ -z "$all_ips" ]]; then
        log "WARNING: No nodes to wait for SSH"
        return 0
    fi

    log "Waiting for SSH readiness on all nodes (timeout: ${max_wait}s)..."
    local start_time
    start_time=$(date +%s)

    local -a ips
    read -ra ips <<< "$all_ips"

    # Build SSH base args — use ProxyCommand instead of -J so options
    # propagate to the jump connection
    local -a ssh_base=(-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ConnectTimeout=10 -o BatchMode=yes)
    if [[ -n "$ssh_key_arg" ]]; then
        ssh_base+=($ssh_key_arg)
    fi

    if [[ -n "${MONITOR_HOST:-}" ]]; then
        ssh_base+=(-o "ProxyCommand=ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ${ssh_key_arg} -W %h:%p ${SSH_USER:-ec2-user}@${MONITOR_HOST}")
    fi

    for ip in "${ips[@]}"; do
        while true; do
            local elapsed=$(( $(date +%s) - start_time ))
            if (( elapsed >= max_wait )); then
                log "ERROR: SSH timeout waiting for ${ip} after ${max_wait}s"
                return 1
            fi
            if ssh "${ssh_base[@]}" "${SSH_USER:-ec2-user}@${ip}" echo ok >/dev/null 2>&1; then
                log "  SSH ready: ${ip} (${elapsed}s)"
                break
            fi
            sleep 5
        done
    done

    local total=$(( $(date +%s) - start_time ))
    log "All nodes SSH-ready in ${total}s"
}

# ---------------------------------------------------------------------------
# Parse inventory for node IPs and set environment
# ---------------------------------------------------------------------------

setup_env_from_inventory() {
    local inventory="${1:-${ANSIBLE_DIR}/inventory/hosts}"
    if [[ ! -f "$inventory" ]]; then
        log "ERROR: Inventory not found at $inventory"
        exit 1
    fi

    # Extract VMQ node IPs (lines under [vmq_nodes] section)
    local vmq_ips=""
    local in_vmq=false
    while IFS= read -r line; do
        if [[ "$line" == "[vmq_nodes]" ]]; then
            in_vmq=true; continue
        elif [[ "$line" == "["* ]]; then
            in_vmq=false; continue
        fi
        if $in_vmq && [[ -n "$line" && "$line" != "#"* ]]; then
            local ip
            ip=$(echo "$line" | awk '{print $1}')
            if [[ -n "$ip" ]]; then
                vmq_ips="${vmq_ips:+$vmq_ips }${ip}"
            fi
        fi
    done < "$inventory"

    # Extract bench node IPs
    local bench_ips=""
    local in_bench=false
    while IFS= read -r line; do
        if [[ "$line" == "[bench_nodes]" ]]; then
            in_bench=true; continue
        elif [[ "$line" == "["* ]]; then
            in_bench=false; continue
        fi
        if $in_bench && [[ -n "$line" && "$line" != "#"* ]]; then
            local ip
            ip=$(echo "$line" | awk '{print $1}')
            if [[ -n "$ip" ]]; then
                bench_ips="${bench_ips:+$bench_ips }${ip}"
            fi
        fi
    done < "$inventory"

    # Extract monitor IP
    local monitor_ip=""
    local in_monitor=false
    while IFS= read -r line; do
        if [[ "$line" == "[monitor]" ]]; then
            in_monitor=true; continue
        elif [[ "$line" == "["* ]]; then
            in_monitor=false; continue
        fi
        if $in_monitor && [[ -n "$line" && "$line" != "#"* ]]; then
            monitor_ip=$(echo "$line" | awk '{print $1}')
            break
        fi
    done < "$inventory"

    # Extract [all:vars] key=value pairs (lb_host, auth credentials)
    local lb_host=""
    local bench_mqtt_username=""
    local bench_mqtt_password=""
    local in_allvars=false
    while IFS= read -r line; do
        if [[ "$line" == "[all:vars]" ]]; then
            in_allvars=true; continue
        elif [[ "$line" == "["* ]]; then
            in_allvars=false; continue
        fi
        if $in_allvars && [[ -n "$line" && "$line" != "#"* ]]; then
            case "$line" in
                lb_host=*) lb_host="${line#lb_host=}" ;;
                bench_mqtt_username=*) bench_mqtt_username="${line#bench_mqtt_username=}" ;;
                bench_mqtt_password=*) bench_mqtt_password="${line#bench_mqtt_password=}" ;;
            esac
        fi
    done < "$inventory"

    export VMQ_NODES="$vmq_ips"
    export BENCH_NODES="$bench_ips"
    if [[ -n "$monitor_ip" ]]; then
        export MONITOR_HOST="$monitor_ip"
        export PROMETHEUS_URL="http://${monitor_ip}:9090"
    else
        log "WARNING: No [monitor] section in inventory. Prometheus metrics will not be collected."
        export MONITOR_HOST=""
        export PROMETHEUS_URL=""
    fi
    export SSH_KEY="${SSH_KEY:-}"
    export SSH_USER="${SSH_USER:-ec2-user}"
    export SSH_OPTS="${SSH_OPTS:--o StrictHostKeyChecking=no -o ConnectTimeout=5${SSH_KEY:+ -i $SSH_KEY}}"
    export LB_HOST="$lb_host"
    export BENCH_MQTT_USERNAME="$bench_mqtt_username"
    export BENCH_MQTT_PASSWORD="$bench_mqtt_password"

    # Auto-detect cluster size if not specified
    if [[ -z "${CLUSTER_SIZE:-}" ]]; then
        local -a nodes
        read -ra nodes <<< "$VMQ_NODES"
        CLUSTER_SIZE="${#nodes[@]}"
    fi

    log "VMQ_NODES:   $VMQ_NODES"
    log "BENCH_NODES: $BENCH_NODES"
    log "MONITOR:     $MONITOR_HOST"
    log "CLUSTER_SIZE: $CLUSTER_SIZE"
    if [[ -n "$lb_host" ]]; then
        log "LB_HOST:     $lb_host"
    fi
    if [[ -n "$bench_mqtt_username" ]]; then
        log "AUTH:        enabled (user: $bench_mqtt_username)"
    fi
}

# ---------------------------------------------------------------------------
# Cluster state reset between scenarios
# ---------------------------------------------------------------------------

reset_cluster_state() {
    log "Resetting cluster state between scenarios..."

    # 1. Stop all emqtt_bench on bench nodes
    local -a bench_ips
    read -ra bench_ips <<< "${BENCH_NODES:-}"
    if [[ ${#bench_ips[@]} -gt 0 ]]; then
        for ip in "${bench_ips[@]}"; do
            ssh ${SSH_OPTS:-} "${SSH_USER:-ec2-user}@${ip}" "pkill -f emqtt_bench || true" 2>/dev/null &
        done
        wait
    fi

    # 2. Wait for connection drain
    log "Waiting 30s for connection drain..."
    sleep 30

    # 3. Restart cluster via ansible
    local -a restart_args=()
    if [[ -n "${BUILD_MODE:-}" ]]; then
        restart_args+=(-e "build_mode=${BUILD_MODE}")
    fi
    run_ansible "restart_cluster.yml" "${restart_args[@]}" || log "WARNING: Cluster restart had issues"

    # 4. Re-apply profile if specified
    if [[ -n "${PROFILE_PATH:-}" ]]; then
        log "Re-applying profile after reset..."
        bash "${SCRIPT_DIR}/apply_profile.sh" \
            --profile "$PROFILE_PATH" \
            --ansible-dir "$ANSIBLE_DIR" 2>&1 | tee -a "${LOG_FILE:-/dev/null}" || true
    fi

    # 5. Stabilization pause
    log "Stabilization pause (30s)..."
    sleep 30
    log "Cluster state reset complete"
}

# ---------------------------------------------------------------------------
# Scenario runner (shared by run_comparison.sh & run_matrix.sh)
# ---------------------------------------------------------------------------

run_scenarios() {
    local scenario_dir="${BENCH_DIR}/scenarios"
    case "${SCENARIOS:-standard}" in
        standard)
            local suite
            suite=$(bash "${scenario_dir}/suite.sh" "${CLUSTER_SIZE:-3}" "${VMQ_VERSION:-unknown}")
            IFS=',' read -ra nums <<< "$suite"
            ;;
        all)
            # Discover all scenario numbers from filenames
            local -a nums=()
            local f
            for f in "${scenario_dir}"/core/[0-9]*.sh "${scenario_dir}"/integration/[0-9]*.sh; do
                [[ -f "$f" ]] || continue
                local n
                n=$(basename "$f" | grep -oE '^[0-9]+')
                nums+=("$n")
            done
            # Sort and deduplicate
            IFS=$'\n' read -ra nums <<< "$(printf '%s\n' "${nums[@]}" | sort -n -u)"
            ;;
        *)
            IFS=',' read -ra nums <<< "${SCENARIOS:-}"
            ;;
    esac

    local first_scenario=true
    for num in "${nums[@]}"; do
        num=$(echo "$num" | xargs)
        local padded
        padded=$(printf "%02d" "$num")
        local script=""
        # Search in subdirectories
        script=$(ls "${scenario_dir}/core/${padded}_"*.sh "${scenario_dir}/integration/${padded}_"*.sh 2>/dev/null | head -1 || true)
        if [[ -z "$script" ]]; then
            log "WARNING: No scenario matching ${padded}"
            continue
        fi

        # Reset cluster between scenarios (not before first)
        if [[ "$first_scenario" == "true" ]]; then
            first_scenario=false
        else
            reset_cluster_state
        fi

        local scenario_name
        scenario_name=$(basename "$script" .sh)
        export SCENARIO_TAG="$scenario_name"

        log "--- Running: $scenario_name ---"
        if bash "$script" 2>&1 | tee -a "${RESULTS_DIR}/run.log"; then
            log "--- $scenario_name: PASSED ---"
        else
            log "--- $scenario_name: FAILED ---"
        fi
    done
}

# ---------------------------------------------------------------------------
# Cleanup trap handler
# ---------------------------------------------------------------------------

cleanup_on_exit() {
    log "Cleaning up: stopping all emqtt_bench processes..."
    local -a bench_ips
    read -ra bench_ips <<< "${BENCH_NODES:-}"
    if [[ ${#bench_ips[@]} -gt 0 ]]; then
        for ip in "${bench_ips[@]}"; do
            ssh ${SSH_OPTS:-} "${SSH_USER:-ec2-user}@${ip}" "pkill -f emqtt_bench || true" 2>/dev/null &
        done
        wait
    fi
}
